# Generated by Django 4.1.1 on 2022-10-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_daily_calories_goal_alter_food_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_calories_goal',
        ),
    ]
