# Generated by Django 4.1.1 on 2022-10-26 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_daily_calories_goal_healthrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_calories_goal',
        ),
    ]
