# Generated by Django 4.1.1 on 2022-10-26 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_profile_daily_calories_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calories_goal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20000), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
