# Generated by Django 4.1.1 on 2022-10-31 12:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_profile_daily_calories_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.IntegerField(verbose_name='Carbs(g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.IntegerField(verbose_name='Fat(g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(verbose_name='Protein(g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.IntegerField(verbose_name='Sodium(mg)'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)], verbose_name='weight(kg)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_calories_goal',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20000), django.core.validators.MinValueValidator(1)], verbose_name='Daily Calories Goal(cal)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(1)], verbose_name='height(cm)'),
        ),
    ]
